version: "3.5"

networks:
  radix-csi-azure-keyvault-example:
    name: radix-csi-azure-keyvault-example

services:
  frontend:
    build:
      context: frontend
    container_name: radix-csi-azure-keyvault-example-frontend_container
    networks:
      - radix-csi-azure-keyvault-example
    ports:
      - "8082:8082" # For local debug only; not exposed in prod
    environment:
      - CONNECTION_STRING=1
    volumes:
      - type: bind
        source: .
        target: /app
