apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: radix-csi-azure-keyvault-example-satr
spec:
  environments:
    - name: dev
      build:
        from: main
    - name: qa
      build:
        from: main
    - name: prod
      build:
        from: release
  components:
    - name: frontend
      src: frontend
      ports:
        - name: http
          port: 8082
      publicPort: http
      variables:
        VAR1: "val1"
      secrets:
        - SECRET2
      secretRefs:
        azureKeyVaults:
          - name: RADIX-APP-SECRETS-3
            path: /mnt/secrets
            items:
              - name: secret1
                envVar: SECRET1
              - name: cert1
                type: key
                alias: "cert1.key"
              - name: cert1
                type: cert
                alias: "cert1.crt"
              - name: cert2
                type: cert
                alias: "cert2.crt"
              - name: cert1
                type: secret
                alias: "cert1.secret"
  dnsAppAlias:
      environment: dev
      component: frontend
